name: Logytics Analysis

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  actions: read
  contents: read
  checks: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Logytics Analysis
        uses: logytics-pro/action@v1
        with:
          logytics-api-key: ${{ secrets.LOGYTICS_API_KEY }}
          workflow-run-id: ${{ github.event.workflow_run.id }}
